### ISSUE TITLE
Does not work on Ruby 2.6

### ISSUE THREAD

**Issue by ilya-konanykhin** [envato/aspect_ratio#2]
Ruby 2.6 introduced constants which can start with non-ASCII capital letters: https://bugs.ruby-lang.org/issues/13770

In this gem we have a *capital* Greek letter Delta `Δ`, so Ruby 2.6. treats it as a constant, and fails with:

```
lib/aspect_ratio.rb:58: dynamic constant assignment (SyntaxError)
    Δx = ((x - xʹ) / 2).to_f.floor
    ^~~
```

**Comment by runlevel5** [comment]
Addressed in https://github.com/envato/aspect_ratio/pull/4
